name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 04:00 UTC
    - cron: "0 4 * * 0"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: Sync from LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION_TOKEN }}
          destination-folder: "solutions"
          verbose: true
          commit-header: "chore: sync LeetCode solutions"
